name: ci

on:
  push:
    paths:
      - "**.py"
      - "**.cpp"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci.yml"


jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - run: python -m pip install mypy flake8 pytest

    - run: mypy .
    - run: flake8

    - run: cmake -B build
    - run: cmake --build build
    - run: ctest --test-dir build -V


  integration:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    env:
      CMAKE_GENERATOR: Ninja

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - run: python -m pip install pytest ninja

    - run: cmake -B build
    - run: cmake --build build
    - run: ctest --test-dir build -V
