name: ci

on:
  push:
    paths:
      - "**.py"
      - ".github/workflows/ci.yml"


jobs:

  python:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - run: python -m pip install mypy flake8 pytest

    - run: mypy .
    - run: flake8
    - run: pytest
